export type GameModes =
    | "GCFF_TRAINING_INFINITE"
    | "GCFF_CHALLENGE_COMBO"
    | "GCFC_TRAINING_INFINITE"
    | "GCFC_CHALLENGE_COMBO"
    | "GDFN_TRAINING_INFINITE"
    | "GDFN_CHALLENGE_COMBO";
